FROM node:18-alpine as base

RUN npm init --yes && \
    npm install -g pnpm

USER node

WORKDIR /home/node/app

COPY --chown=node:node package.json ./

RUN pnpm install

COPY --chown=node:node . .

RUN pnpm build

FROM node:18-alpine

EXPOSE 8080

RUN npm init --yes && \
    npm install -g pnpm

USER node

WORKDIR /home/node/app

COPY --chown=node:node package.json ./

RUN pnpm install --prod

COPY --chown=node:node --from=base /home/node/app/dist ./dist

CMD [ "node", "dist/start.js" ]
